ARG RUNNER_VERSION=2.323.0
ARG DEB_S3_VERSION=24.6.0

FROM ghcr.io/actions/actions-runner:${RUNNER_VERSION}

USER root

RUN apt-get update
RUN apt-get install -y --no-install-recommends rubygems
RUN gem install deb-s3 -v "${DEB_S3_VERSION}"

USER runner