name: Build and Push Docker Image
description: Builds and pushes a Docker image using metadata and versioning.

inputs:
  dockerfile-path:
    description: Path to the Dockerfile
    required: true
  image-name:
    description: Full Docker image name (e.g. ghcr.io/owner/repo)
    required: true
  version:
    description: Version to tag the image with
    required: true
  build-args:
    description: Optional newline-separated build arguments (e.g. "ARG1=value\nARG2=value")
    required: false
  build-secrets:
    description: Sensitive information, such as a password or API token, consumed as part of the build process
    required: false

runs:
  using: "composite"
  steps:
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-name }}
        tags: |
          type=raw,value=${{ inputs.version }}
          type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        file: ${{ inputs.dockerfile-path }}
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        secrets: | 
          ${{ inputs.build-secrets }}

        build-args: |
          ${{ inputs.build-args }}